# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
#disqus: dbyll
#google_analytics: dbyll
title: raz's blog

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: raz's blog

description: my very own blog where i wrote about js, gnulinux and hackthebox machines
author:
  name: raz lupercio
  email: raz@lupercio.mx
  github: razlupercio
  twitter: razlupercio
  #pinterest: asd123
  #linkedin: asd123
  bio: infosec consultant
  email_md5: 1a33d02cdcae7c9d310157266d739e44

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
#sidebar_background_image: http://blog.lupercio.mx/assets/media/santiago.jpg

BASE_PATH:

plugins:
  - jekyll-paginate
